
import __ASTRO_IMAGE_IMPORT_Z2hW45l from "../../assets/domain-semantics-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffrom-structure-to-meaning-a-practical-design-lens.md";
import __ASTRO_IMAGE_IMPORT_Z9otA9 from "../../assets/rag-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fretrieval-augmented-generation-rag.md";
import __ASTRO_IMAGE_IMPORT_DC4x0 from "../../assets/board-game-ai-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fboard-game-ai-development.md";
import __ASTRO_IMAGE_IMPORT_225oq7 from "../../assets/react-dev-tips-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-dev-tips.md";
import __ASTRO_IMAGE_IMPORT_Z1VqgzP from "../../assets/javascript-data-visualization-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript-data-visualization-frameworks.md";
import __ASTRO_IMAGE_IMPORT_Z1OV0iS from "../../assets/worktree-refactor-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fworktree-refactor-playbook.md";
import __ASTRO_IMAGE_IMPORT_Z9FH7w from "../../assets/domain-semantics-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-maintain-domain-semantics-in-real-systems.md";
export default new Map([["../../assets/domain-semantics-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffrom-structure-to-meaning-a-practical-design-lens.md", __ASTRO_IMAGE_IMPORT_Z2hW45l], ["../../assets/rag-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fretrieval-augmented-generation-rag.md", __ASTRO_IMAGE_IMPORT_Z9otA9], ["../../assets/board-game-ai-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fboard-game-ai-development.md", __ASTRO_IMAGE_IMPORT_DC4x0], ["../../assets/react-dev-tips-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-dev-tips.md", __ASTRO_IMAGE_IMPORT_225oq7], ["../../assets/javascript-data-visualization-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript-data-visualization-frameworks.md", __ASTRO_IMAGE_IMPORT_Z1VqgzP], ["../../assets/worktree-refactor-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fworktree-refactor-playbook.md", __ASTRO_IMAGE_IMPORT_Z1OV0iS], ["../../assets/domain-semantics-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-maintain-domain-semantics-in-real-systems.md", __ASTRO_IMAGE_IMPORT_Z9FH7w]]);
		