
import __ASTRO_IMAGE_IMPORT_13uydQ from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fboard-game-ai-development.md";
import __ASTRO_IMAGE_IMPORT_ZSX8QJ from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-native-meteor-social-login.md";
import __ASTRO_IMAGE_IMPORT_fNb8 from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-dev-tips.md";
import __ASTRO_IMAGE_IMPORT_ZulDpU from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_1NHVvs from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthird-post.md";
import __ASTRO_IMAGE_IMPORT_1inyCS from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecond-post.md";
import __ASTRO_IMAGE_IMPORT_MGbyL from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fusing-mdx.mdx";
import __ASTRO_IMAGE_IMPORT_Z1Yq4sn from "../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1F4X4R from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1zVlFS from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript-data-visualization-frameworks.md";
import __ASTRO_IMAGE_IMPORT_Z1VqgzP from "../../assets/javascript-data-visualization-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript-data-visualization-frameworks.md";
import __ASTRO_IMAGE_IMPORT_Z9otA9 from "../../assets/rag-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fretrieval-augmented-generation-rag.md";
import __ASTRO_IMAGE_IMPORT_1135uJ from "../../assets/vibe-coding-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvibe-coding-csharp-dotnet.md";
import __ASTRO_IMAGE_IMPORT_1YVwGU from "../../assets/react-native-meteor-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-native-meteor-social-login.md";
import __ASTRO_IMAGE_IMPORT_DC4x0 from "../../assets/board-game-ai-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fboard-game-ai-development.md";
import __ASTRO_IMAGE_IMPORT_225oq7 from "../../assets/react-dev-tips-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-dev-tips.md";
export default new Map([["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fboard-game-ai-development.md", __ASTRO_IMAGE_IMPORT_13uydQ], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-native-meteor-social-login.md", __ASTRO_IMAGE_IMPORT_ZSX8QJ], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-dev-tips.md", __ASTRO_IMAGE_IMPORT_fNb8], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_ZulDpU], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthird-post.md", __ASTRO_IMAGE_IMPORT_1NHVvs], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecond-post.md", __ASTRO_IMAGE_IMPORT_1inyCS], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fusing-mdx.mdx", __ASTRO_IMAGE_IMPORT_MGbyL], ["../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_Z1Yq4sn], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_Z1F4X4R], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript-data-visualization-frameworks.md", __ASTRO_IMAGE_IMPORT_Z1zVlFS], ["../../assets/javascript-data-visualization-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjavascript-data-visualization-frameworks.md", __ASTRO_IMAGE_IMPORT_Z1VqgzP], ["../../assets/rag-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fretrieval-augmented-generation-rag.md", __ASTRO_IMAGE_IMPORT_Z9otA9], ["../../assets/vibe-coding-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvibe-coding-csharp-dotnet.md", __ASTRO_IMAGE_IMPORT_1135uJ], ["../../assets/react-native-meteor-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-native-meteor-social-login.md", __ASTRO_IMAGE_IMPORT_1YVwGU], ["../../assets/board-game-ai-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fboard-game-ai-development.md", __ASTRO_IMAGE_IMPORT_DC4x0], ["../../assets/react-dev-tips-hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-dev-tips.md", __ASTRO_IMAGE_IMPORT_225oq7]]);
		